[package]
name = "rocket-embed-serve"
version = "0.1.0"
authors = ["gabriel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed = "5.2.0"
rocket = "0.4.2"

[features]
index = []