[package]
name = "rust-embed-rocket"
version = "0.1.0"
authors = ["gabriel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed = "5.9.0"
rocket = 0.5.0-rc.1"
